import { Incident } from "@/types/incident";
import { FireStation } from "@/types/station";
import { EmergencyVehicle } from "@/types/vehicle";
import { Personnel } from "@/types/personnel";
import { EocSystemStatus, WardMetric, ResponseTimeMetric, IncidentTypeDistribution, ComplianceReport } from "@/types/telemetry";

export const MOCK_SYSTEM_STATUS: EocSystemStatus = {
  defconLevel: "CONDITION_RED",
  activeIncidentsCount: 3,
  availableVehiclesCount: 9,
  totalVehiclesCount: 14,
  personnelOnDutyCount: 28,
  totalPersonnelCount: 42,
  avgResponseTimeMin: 5.8,
  hydrantNetworkHealthPct: 94.2,
  weatherTempC: 31.4,
  weatherHumidityPct: 76,
  weatherWindKmh: 14.8,
  weatherWindDir: "WSW (245°)",
  radioFrequencyMhz: 156.8,
  telemetryLinkStatus: "ONLINE",
  lastSyncTimestamp: "2026-09-10T15:37:00.000Z",
};

export const MOCK_STATIONS: FireStation[] = [
  {
    id: "STN-01",
    code: "MR-01",
    name: "Station 1 - Mira Road East",
    ward: "Ward 1 - Mira Road East",
    address: "Opp. GCC Club, Mira Bhayandar Road, Mira Road (E), Thane - 401107",
    officerInCharge: "Suresh P. Jadhav",
    officerRank: "Station Officer (SO)",
    phone: "+91-22-2811-3011",
    emergencyHotline: "101 / +91-22-2811-2988",
    status: "HIGH_ACTIVITY",
    coordinates: { lat: 19.2812, lng: 72.8715 },
    baysTotal: 4,
    baysOccupied: 3,
    waterReserveLiters: 45000,
    waterMaxCapacityLiters: 50000,
    foamReserveLiters: 6500,
    personnelTotal: 12,
    personnelOnDuty: 9,
    vehiclesAssignedIds: ["MBMC-FE-01", "MBMC-FE-04", "MBMC-FE-08", "MBMC-FE-12"],
    activeIncidentsCount: 1,
    coverageRadiusKm: 4.8,
    turnoutTimeAvgSeconds: 52,
    hydrantsNearby: [
      { id: "HYD-MR-01", location: "GCC Club Junction", pressureBar: 5.8, flowRateLpm: 1200, status: "ACTIVE", distanceMeters: 180, coordinates: { lat: 19.282, lng: 72.872 } },
      { id: "HYD-MR-02", location: "Kanakia Park Main Gate", pressureBar: 5.2, flowRateLpm: 1100, status: "ACTIVE", distanceMeters: 420, coordinates: { lat: 19.284, lng: 72.875 } },
      { id: "HYD-MR-03", location: "Poonam Sagar Ring Road", pressureBar: 4.1, flowRateLpm: 950, status: "ACTIVE", distanceMeters: 650, coordinates: { lat: 19.285, lng: 72.868 } },
    ],
  },
  {
    id: "STN-02",
    code: "BW-02",
    name: "Station 2 - Bhayandar West Central",
    ward: "Ward 4 - Bhayandar West",
    address: "Near MBMC Netaji Subhash Chandra Bose Stadium, Bhayandar (W) - 401101",
    officerInCharge: "Kailash R. Patil",
    officerRank: "Divisional Fire Officer (DFO)",
    phone: "+91-22-2819-4422",
    emergencyHotline: "101 / +91-22-2811-1999",
    status: "OPERATIONAL",
    coordinates: { lat: 19.3085, lng: 72.8524 },
    baysTotal: 5,
    baysOccupied: 4,
    waterReserveLiters: 80000,
    waterMaxCapacityLiters: 80000,
    foamReserveLiters: 12000,
    personnelTotal: 14,
    personnelOnDuty: 10,
    vehiclesAssignedIds: ["MBMC-FE-02", "MBMC-FE-05", "MBMC-FE-09", "MBMC-FE-14"],
    activeIncidentsCount: 0,
    coverageRadiusKm: 5.2,
    turnoutTimeAvgSeconds: 48,
    hydrantsNearby: [
      { id: "HYD-BW-01", location: "Stadium Main Gate", pressureBar: 6.2, flowRateLpm: 1400, status: "ACTIVE", distanceMeters: 120, coordinates: { lat: 19.309, lng: 72.853 } },
      { id: "HYD-BW-02", location: "Bhayandar Railway Stn (W)", pressureBar: 5.4, flowRateLpm: 1150, status: "ACTIVE", distanceMeters: 750, coordinates: { lat: 19.303, lng: 72.855 } },
    ],
  },
  {
    id: "STN-03",
    code: "BE-03",
    name: "Station 3 - Bhayandar East (MIDC Industrial)",
    ward: "Ward 3 - Bhayandar East",
    address: "Road No. 12, Subhash Chandra Bose MIDC Industrial Estate, Bhayandar (E) - 401105",
    officerInCharge: "Vinod M. Gharat",
    officerRank: "Station Officer (SO)",
    phone: "+91-22-2815-1100",
    emergencyHotline: "101 / +91-22-2815-1101",
    status: "HIGH_ACTIVITY",
    coordinates: { lat: 19.2965, lng: 72.8642 },
    baysTotal: 4,
    baysOccupied: 4,
    waterReserveLiters: 60000,
    waterMaxCapacityLiters: 60000,
    foamReserveLiters: 18000,
    personnelTotal: 10,
    personnelOnDuty: 8,
    vehiclesAssignedIds: ["MBMC-FE-06", "MBMC-FE-07", "MBMC-FE-10"],
    activeIncidentsCount: 1,
    coverageRadiusKm: 4.5,
    turnoutTimeAvgSeconds: 44,
    hydrantsNearby: [
      { id: "HYD-BE-01", location: "MIDC Sector 3 High-Pressure Point", pressureBar: 6.8, flowRateLpm: 1800, status: "ACTIVE", distanceMeters: 90, coordinates: { lat: 19.297, lng: 72.865 } },
      { id: "HYD-BE-02", location: "Godown Line Crossroad", pressureBar: 5.0, flowRateLpm: 1250, status: "ACTIVE", distanceMeters: 310, coordinates: { lat: 19.295, lng: 72.863 } },
    ],
  },
  {
    id: "STN-04",
    code: "KM-04",
    name: "Station 4 - Kashimira (WEH Corridor)",
    ward: "Ward 5 - Kashimira & WEH",
    address: "Near Kashimira Flyover Toll Naka, Western Express Highway - 401104",
    officerInCharge: "Anil B. Deshmukh",
    officerRank: "Station Officer (SO)",
    phone: "+91-22-2845-9800",
    emergencyHotline: "101 / +91-22-2845-9801",
    status: "OPERATIONAL",
    coordinates: { lat: 19.2625, lng: 72.8835 },
    baysTotal: 3,
    baysOccupied: 2,
    waterReserveLiters: 35000,
    waterMaxCapacityLiters: 40000,
    foamReserveLiters: 4500,
    personnelTotal: 8,
    personnelOnDuty: 6,
    vehiclesAssignedIds: ["MBMC-FE-03", "MBMC-FE-11"],
    activeIncidentsCount: 1,
    coverageRadiusKm: 6.0,
    turnoutTimeAvgSeconds: 50,
    hydrantsNearby: [
      { id: "HYD-KM-01", location: "Kashimira Police Station Junction", pressureBar: 5.5, flowRateLpm: 1300, status: "ACTIVE", distanceMeters: 200, coordinates: { lat: 19.263, lng: 72.884 } },
    ],
  },
  {
    id: "STN-05",
    code: "UT-05",
    name: "Station 5 - Uttan Coastal Sub-Station",
    ward: "Ward 6 - Uttan & Coastal",
    address: "Uttan Lighthouse Road, Near Dongri Creek, Uttan - 401106",
    officerInCharge: "Ganesh T. Mhatre",
    officerRank: "Sub-Officer (Sub-O)",
    phone: "+91-22-2804-1234",
    emergencyHotline: "101",
    status: "STANDBY",
    coordinates: { lat: 19.281, lng: 72.784 },
    baysTotal: 2,
    baysOccupied: 1,
    waterReserveLiters: 25000,
    waterMaxCapacityLiters: 30000,
    foamReserveLiters: 2000,
    personnelTotal: 6,
    personnelOnDuty: 4,
    vehiclesAssignedIds: ["MBMC-FE-13"],
    activeIncidentsCount: 0,
    coverageRadiusKm: 7.5,
    turnoutTimeAvgSeconds: 58,
    hydrantsNearby: [
      { id: "HYD-UT-01", location: "Uttan Fishing Jetty Point", pressureBar: 4.8, flowRateLpm: 1000, status: "ACTIVE", distanceMeters: 450, coordinates: { lat: 19.282, lng: 72.785 } },
    ],
  },
];

export const MOCK_VEHICLES: EmergencyVehicle[] = [
  {
    id: "MBMC-FE-01",
    registrationNumber: "MH-04-FE-2024",
    callSign: "Tender Alpha 1",
    name: "Heavy Multi-Purpose Water Tender 01",
    type: "Water Tender (Heavy)",
    stationId: "STN-01",
    stationName: "Station 1 - Mira Road East",
    status: "ON_SCENE_PUMPING",
    driverName: "Dinesh K. Sawant",
    commanderName: "Suresh P. Jadhav (SO)",
    crewCapacity: 6,
    assignedCrewCount: 6,
    assignedIncidentId: "INC-2026-00421",
    waterCapacityLiters: 12000,
    foamCapacityLiters: 1500,
    pumpCapacityLpm: 4000,
    serviceMileageKm: 18450,
    nextServiceDate: "2026-11-15",
    image: "/images/fire-engine-front.jpg",
    telemetry: {
      speedKmh: 0,
      engineRpm: 2100,
      waterLevelPct: 62,
      waterRemainingLiters: 7440,
      foamLevelPct: 88,
      foamRemainingLiters: 1320,
      fuelLevelPct: 82,
      pumpPressurePsi: 135,
      dischargeLpm: 1850,
      batteryHealthPct: 98,
      engineTempC: 88,
      latitude: 19.2845,
      longitude: 72.8732,
      headingDeg: 120,
      lastPing: "Just now",
    },
  },
  {
    id: "MBMC-FE-04",
    registrationNumber: "MH-04-FE-4088",
    callSign: "Bronto Skylift 55",
    name: "55-Meter Hydraulic Aerial Ladder Platform",
    type: "55m Hydraulic Aerial Ladder (Bronto)",
    stationId: "STN-01",
    stationName: "Station 1 - Mira Road East",
    status: "ON_SCENE_PUMPING",
    driverName: "Pradeep B. Naik",
    commanderName: "Rameshwar Gurav (LFM)",
    crewCapacity: 4,
    assignedCrewCount: 4,
    assignedIncidentId: "INC-2026-00421",
    waterCapacityLiters: 4000,
    foamCapacityLiters: 500,
    pumpCapacityLpm: 3500,
    ladderReachMeters: 55,
    serviceMileageKm: 9200,
    nextServiceDate: "2026-12-01",
    image: "/images/fire-engine-side.jpg",
    telemetry: {
      speedKmh: 0,
      engineRpm: 1800,
      waterLevelPct: 75,
      waterRemainingLiters: 3000,
      foamLevelPct: 95,
      foamRemainingLiters: 475,
      fuelLevelPct: 79,
      pumpPressurePsi: 140,
      dischargeLpm: 1200,
      batteryHealthPct: 99,
      engineTempC: 84,
      latitude: 19.2846,
      longitude: 72.8735,
      headingDeg: 90,
      lastPing: "Just now",
    },
  },
  {
    id: "MBMC-FE-06",
    registrationNumber: "MH-04-FE-6102",
    callSign: "Foam Strike 06",
    name: "High-Capacity Foam Crash Tender",
    type: "Foam Crash Tender",
    stationId: "STN-03",
    stationName: "Station 3 - Bhayandar East (MIDC)",
    status: "ON_SCENE_PUMPING",
    driverName: "Santosh G. More",
    commanderName: "Vinod M. Gharat (SO)",
    crewCapacity: 5,
    assignedCrewCount: 5,
    assignedIncidentId: "INC-2026-00420",
    waterCapacityLiters: 9000,
    foamCapacityLiters: 4000,
    pumpCapacityLpm: 5000,
    serviceMileageKm: 14200,
    nextServiceDate: "2026-10-20",
    image: "/images/fire-engine-fleet.jpg",
    telemetry: {
      speedKmh: 0,
      engineRpm: 2400,
      waterLevelPct: 48,
      waterRemainingLiters: 4320,
      foamLevelPct: 52,
      foamRemainingLiters: 2080,
      fuelLevelPct: 71,
      pumpPressurePsi: 160,
      dischargeLpm: 2800,
      batteryHealthPct: 96,
      engineTempC: 92,
      latitude: 19.2978,
      longitude: 72.8655,
      headingDeg: 45,
      lastPing: "Just now",
    },
  },
  {
    id: "MBMC-FE-07",
    registrationNumber: "MH-04-FE-7119",
    callSign: "Hazmat Recon 07",
    name: "Hazmat & Chemical Defense Unit",
    type: "Hazmat / Chemical Response Unit",
    stationId: "STN-03",
    stationName: "Station 3 - Bhayandar East (MIDC)",
    status: "ON_SCENE_PUMPING",
    driverName: "Rohan D. Kamble",
    commanderName: "Mahesh A. Joshi (Sub-O)",
    crewCapacity: 4,
    assignedCrewCount: 4,
    assignedIncidentId: "INC-2026-00420",
    waterCapacityLiters: 2000,
    foamCapacityLiters: 2000,
    pumpCapacityLpm: 2500,
    serviceMileageKm: 8100,
    nextServiceDate: "2027-01-10",
    image: "/images/fire-engine-side.jpg",
    telemetry: {
      speedKmh: 0,
      engineRpm: 1200,
      waterLevelPct: 90,
      waterRemainingLiters: 1800,
      foamLevelPct: 70,
      foamRemainingLiters: 1400,
      fuelLevelPct: 85,
      pumpPressurePsi: 80,
      dischargeLpm: 600,
      batteryHealthPct: 97,
      engineTempC: 80,
      latitude: 19.2981,
      longitude: 72.8658,
      headingDeg: 270,
      lastPing: "Just now",
    },
  },
  {
    id: "MBMC-FE-03",
    registrationNumber: "MH-04-FE-3011",
    callSign: "QRV Rapid 03",
    name: "Quick Response Multi-Rescue Vehicle",
    type: "Quick Response Vehicle (QRV)",
    stationId: "STN-04",
    stationName: "Station 4 - Kashimira",
    status: "EN_ROUTE",
    driverName: "Amit V. Rane",
    commanderName: "Anil B. Deshmukh (SO)",
    crewCapacity: 4,
    assignedCrewCount: 4,
    assignedIncidentId: "INC-2026-00419",
    waterCapacityLiters: 1500,
    foamCapacityLiters: 300,
    pumpCapacityLpm: 2000,
    serviceMileageKm: 22400,
    nextServiceDate: "2026-11-30",
    image: "/images/fire-engine-front.jpg",
    telemetry: {
      speedKmh: 54,
      engineRpm: 2600,
      waterLevelPct: 100,
      waterRemainingLiters: 1500,
      foamLevelPct: 100,
      foamRemainingLiters: 300,
      fuelLevelPct: 92,
      pumpPressurePsi: 0,
      dischargeLpm: 0,
      batteryHealthPct: 98,
      engineTempC: 85,
      latitude: 19.2715,
      longitude: 72.879,
      headingDeg: 315,
      lastPing: "10s ago",
    },
  },
  {
    id: "MBMC-FE-02",
    registrationNumber: "MH-04-FE-2015",
    callSign: "Pumper Bravo 2",
    name: "Standard Multi-Purpose Pumper 02",
    type: "Multi-Purpose Pumper",
    stationId: "STN-02",
    stationName: "Station 2 - Bhayandar West",
    status: "AVAILABLE_IN_STATION",
    driverName: "Sachin M. Kadam",
    commanderName: "Kailash R. Patil (DFO)",
    crewCapacity: 6,
    assignedCrewCount: 6,
    waterCapacityLiters: 6000,
    foamCapacityLiters: 800,
    pumpCapacityLpm: 3200,
    serviceMileageKm: 31200,
    nextServiceDate: "2026-10-15",
    image: "/images/fire-engine-side.jpg",
    telemetry: {
      speedKmh: 0,
      engineRpm: 0,
      waterLevelPct: 100,
      waterRemainingLiters: 6000,
      foamLevelPct: 100,
      foamRemainingLiters: 800,
      fuelLevelPct: 95,
      pumpPressurePsi: 0,
      dischargeLpm: 0,
      batteryHealthPct: 100,
      engineTempC: 32,
      latitude: 19.3085,
      longitude: 72.8524,
      headingDeg: 0,
      lastPing: "Just now",
    },
  },
  {
    id: "MBMC-FE-05",
    registrationNumber: "MH-04-FE-5022",
    callSign: "Heavy Tanker 05",
    name: "Mega Water Bowser 16,000L",
    type: "Water Tender (Heavy)",
    stationId: "STN-02",
    stationName: "Station 2 - Bhayandar West",
    status: "AVAILABLE_IN_STATION",
    driverName: "Nitin S. Bhole",
    commanderName: "Mangesh T. Tare (LFM)",
    crewCapacity: 3,
    assignedCrewCount: 3,
    waterCapacityLiters: 16000,
    foamCapacityLiters: 500,
    pumpCapacityLpm: 2500,
    serviceMileageKm: 19800,
    nextServiceDate: "2026-12-20",
    image: "/images/fire-engine-fleet.jpg",
    telemetry: {
      speedKmh: 0,
      engineRpm: 0,
      waterLevelPct: 100,
      waterRemainingLiters: 16000,
      foamLevelPct: 100,
      foamRemainingLiters: 500,
      fuelLevelPct: 90,
      pumpPressurePsi: 0,
      dischargeLpm: 0,
      batteryHealthPct: 99,
      engineTempC: 30,
      latitude: 19.3086,
      longitude: 72.8525,
      headingDeg: 0,
      lastPing: "Just now",
    },
  },
  {
    id: "MBMC-FE-08",
    registrationNumber: "MH-04-FE-8033",
    callSign: "Rescue Van 08",
    name: "Heavy Extrication & Rescue Van",
    type: "Emergency Rescue Van",
    stationId: "STN-01",
    stationName: "Station 1 - Mira Road East",
    status: "AVAILABLE_IN_STATION",
    driverName: "Vikram R. Shinde",
    commanderName: "Anand M. Solanki (Sub-O)",
    crewCapacity: 5,
    assignedCrewCount: 5,
    waterCapacityLiters: 500,
    foamCapacityLiters: 100,
    pumpCapacityLpm: 1000,
    serviceMileageKm: 16300,
    nextServiceDate: "2027-02-10",
    image: "/images/fire-engine-side.jpg",
    telemetry: {
      speedKmh: 0,
      engineRpm: 0,
      waterLevelPct: 100,
      waterRemainingLiters: 500,
      foamLevelPct: 100,
      foamRemainingLiters: 100,
      fuelLevelPct: 88,
      pumpPressurePsi: 0,
      dischargeLpm: 0,
      batteryHealthPct: 98,
      engineTempC: 31,
      latitude: 19.2812,
      longitude: 72.8715,
      headingDeg: 0,
      lastPing: "Just now",
    },
  },
  {
    id: "MBMC-FE-09",
    registrationNumber: "MH-04-FE-9044",
    callSign: "ALS Medic 09",
    name: "Advanced Life Support Cardiac Ambulance",
    type: "Advanced Life Support Ambulance",
    stationId: "STN-02",
    stationName: "Station 2 - Bhayandar West",
    status: "AVAILABLE_IN_STATION",
    driverName: "Deepak S. Salve",
    commanderName: "Dr. Farhan Qureshi (Paramedic)",
    crewCapacity: 3,
    assignedCrewCount: 3,
    waterCapacityLiters: 0,
    foamCapacityLiters: 0,
    pumpCapacityLpm: 0,
    serviceMileageKm: 27500,
    nextServiceDate: "2026-10-30",
    image: "/images/fire-engine-front.jpg",
    telemetry: {
      speedKmh: 0,
      engineRpm: 0,
      waterLevelPct: 0,
      waterRemainingLiters: 0,
      foamLevelPct: 0,
      foamRemainingLiters: 0,
      fuelLevelPct: 94,
      pumpPressurePsi: 0,
      dischargeLpm: 0,
      batteryHealthPct: 100,
      engineTempC: 30,
      latitude: 19.3085,
      longitude: 72.8524,
      headingDeg: 0,
      lastPing: "Just now",
    },
  },
  {
    id: "MBMC-FE-10",
    registrationNumber: "MH-04-FE-1055",
    callSign: "Pumper MIDC 10",
    name: "Industrial Pumper 10",
    type: "Multi-Purpose Pumper",
    stationId: "STN-03",
    stationName: "Station 3 - Bhayandar East (MIDC)",
    status: "AVAILABLE_IN_STATION",
    driverName: "Prakash T. Dalvi",
    commanderName: "Sharad B. Kadam (LFM)",
    crewCapacity: 6,
    assignedCrewCount: 6,
    waterCapacityLiters: 8000,
    foamCapacityLiters: 1200,
    pumpCapacityLpm: 3600,
    serviceMileageKm: 15400,
    nextServiceDate: "2026-11-20",
    image: "/images/fire-engine-side.jpg",
    telemetry: {
      speedKmh: 0,
      engineRpm: 0,
      waterLevelPct: 100,
      waterRemainingLiters: 8000,
      foamLevelPct: 100,
      foamRemainingLiters: 1200,
      fuelLevelPct: 86,
      pumpPressurePsi: 0,
      dischargeLpm: 0,
      batteryHealthPct: 97,
      engineTempC: 31,
      latitude: 19.2965,
      longitude: 72.8642,
      headingDeg: 0,
      lastPing: "Just now",
    },
  },
  {
    id: "MBMC-FE-11",
    registrationNumber: "MH-04-FE-1166",
    callSign: "Tender Kashimira 11",
    name: "High-Rise Pumper Tender 11",
    type: "Multi-Purpose Pumper",
    stationId: "STN-04",
    stationName: "Station 4 - Kashimira",
    status: "AVAILABLE_IN_STATION",
    driverName: "Sanjay N. Bagwe",
    commanderName: "Harish C. More (Sub-O)",
    crewCapacity: 6,
    assignedCrewCount: 6,
    waterCapacityLiters: 6000,
    foamCapacityLiters: 800,
    pumpCapacityLpm: 3200,
    serviceMileageKm: 21900,
    nextServiceDate: "2026-12-12",
    image: "/images/fire-engine-front.jpg",
    telemetry: {
      speedKmh: 0,
      engineRpm: 0,
      waterLevelPct: 100,
      waterRemainingLiters: 6000,
      foamLevelPct: 100,
      foamRemainingLiters: 800,
      fuelLevelPct: 91,
      pumpPressurePsi: 0,
      dischargeLpm: 0,
      batteryHealthPct: 99,
      engineTempC: 30,
      latitude: 19.2625,
      longitude: 72.8835,
      headingDeg: 0,
      lastPing: "Just now",
    },
  },
  {
    id: "MBMC-FE-12",
    registrationNumber: "MH-04-FE-1277",
    callSign: "ALS Medic 12",
    name: "Rapid Trauma Medic Van",
    type: "Advanced Life Support Ambulance",
    stationId: "STN-01",
    stationName: "Station 1 - Mira Road East",
    status: "AVAILABLE_IN_STATION",
    driverName: "Ashok K. Jadhav",
    commanderName: "Dr. Sneha Verma (EMT)",
    crewCapacity: 3,
    assignedCrewCount: 3,
    waterCapacityLiters: 0,
    foamCapacityLiters: 0,
    pumpCapacityLpm: 0,
    serviceMileageKm: 12800,
    nextServiceDate: "2027-01-25",
    image: "/images/fire-engine-side.jpg",
    telemetry: {
      speedKmh: 0,
      engineRpm: 0,
      waterLevelPct: 0,
      waterRemainingLiters: 0,
      foamLevelPct: 0,
      foamRemainingLiters: 0,
      fuelLevelPct: 96,
      pumpPressurePsi: 0,
      dischargeLpm: 0,
      batteryHealthPct: 100,
      engineTempC: 30,
      latitude: 19.2812,
      longitude: 72.8715,
      headingDeg: 0,
      lastPing: "Just now",
    },
  },
  {
    id: "MBMC-FE-13",
    registrationNumber: "MH-04-FE-1388",
    callSign: "Coastal Tender 13",
    name: "Coastal All-Terrain Water Tender 13",
    type: "Water Tender (Heavy)",
    stationId: "STN-05",
    stationName: "Station 5 - Uttan Coastal Sub-Station",
    status: "AVAILABLE_IN_STATION",
    driverName: "Umesh G. Tandel",
    commanderName: "Ganesh T. Mhatre (Sub-O)",
    crewCapacity: 4,
    assignedCrewCount: 4,
    waterCapacityLiters: 8000,
    foamCapacityLiters: 1000,
    pumpCapacityLpm: 3000,
    serviceMileageKm: 11200,
    nextServiceDate: "2026-11-05",
    image: "/images/fire-engine-fleet.jpg",
    telemetry: {
      speedKmh: 0,
      engineRpm: 0,
      waterLevelPct: 100,
      waterRemainingLiters: 8000,
      foamLevelPct: 100,
      foamRemainingLiters: 1000,
      fuelLevelPct: 89,
      pumpPressurePsi: 0,
      dischargeLpm: 0,
      batteryHealthPct: 98,
      engineTempC: 30,
      latitude: 19.281,
      longitude: 72.784,
      headingDeg: 0,
      lastPing: "Just now",
    },
  },
  {
    id: "MBMC-FE-14",
    registrationNumber: "MH-04-FE-1499",
    callSign: "Pumper Reserve 14",
    name: "Fleet Reserve Pumper 14",
    type: "Multi-Purpose Pumper",
    stationId: "STN-02",
    stationName: "Station 2 - Bhayandar West",
    status: "IN_MAINTENANCE",
    driverName: "Assigned to Workshop",
    commanderName: "Workshop Chief M. Rao",
    crewCapacity: 6,
    assignedCrewCount: 0,
    waterCapacityLiters: 6000,
    foamCapacityLiters: 800,
    pumpCapacityLpm: 3200,
    serviceMileageKm: 48900,
    nextServiceDate: "2026-09-12",
    image: "/images/fire-engine-front.jpg",
    telemetry: {
      speedKmh: 0,
      engineRpm: 0,
      waterLevelPct: 10,
      waterRemainingLiters: 600,
      foamLevelPct: 20,
      foamRemainingLiters: 160,
      fuelLevelPct: 40,
      pumpPressurePsi: 0,
      dischargeLpm: 0,
      batteryHealthPct: 82,
      engineTempC: 28,
      latitude: 19.3085,
      longitude: 72.8524,
      headingDeg: 0,
      lastPing: "1 hour ago",
    },
  },
];

export const MOCK_INCIDENTS: Incident[] = [
  {
    id: "INC-2026-00421",
    incidentNumber: "INC-2026-00421",
    title: "Multi-Story Residential Complex Fire (8th Floor)",
    type: "High-Rise Building Rescue",
    severity: "CRITICAL",
    status: "ON_SCENE",
    reportedAt: "2026-09-10T14:32:00.000Z",
    callerName: "Rajesh S. Sharma (Secretary)",
    callerPhone: "+91 98201 44521",
    location: {
      address: "Building B-4, Poonam Sagar Complex, Sector 9",
      landmark: "Near GCC Club & Shanti Park Junction",
      ward: "Ward 1 - Mira Road East",
      zone: "Zone A (North-East)",
      lat: 19.2845,
      lng: 72.8732,
      gridRef: "MB-MR-08A",
    },
    leadStationId: "STN-01",
    leadStationName: "Station 1 - Mira Road East",
    assignedUnits: [
      {
        unitId: "MBMC-FE-01",
        callSign: "Tender Alpha 1",
        type: "Water Tender (Heavy)",
        stationName: "Station 1 - Mira Road East",
        dispatchedAt: "14:34:10",
        etaMinutes: 0,
        status: "ON_SCENE",
        crewCount: 6,
        commander: "Suresh P. Jadhav (SO)",
      },
      {
        unitId: "MBMC-FE-04",
        callSign: "Bronto Skylift 55",
        type: "55m Hydraulic Aerial Ladder",
        stationName: "Station 1 - Mira Road East",
        dispatchedAt: "14:35:40",
        etaMinutes: 0,
        status: "ON_SCENE",
        crewCount: 4,
        commander: "Rameshwar Gurav (LFM)",
      },
    ],
    casualtiesReported: 0,
    peopleEvacuated: 46,
    structuresAtRisk: 3,
    waterSupplyStatus: "HYDRANT_CONNECTED",
    hazmatPresent: false,
    windSpeedKmh: 14.8,
    windDirection: "WSW (245°)",
    radioChannel: "CH-01 (156.800 MHz)",
    cadNotes: "Heavy black smoke billowing from Flat 803 electrical duct. Aerial ladder Bronto 55 deployed for 8th/9th floor ventilation and rooftop evacuation. All residents accounted for. Main power grid isolated.",
    timeline: [
      {
        id: "TL-01",
        timestamp: "14:32:15",
        title: "Emergency 101 Call Received",
        description: "Caller reports intense smoke from 8th-floor duct spreading to higher floors.",
        author: "CAD Operator R. Dave",
        type: "DISPATCH",
      },
      {
        id: "TL-02",
        timestamp: "14:34:10",
        title: "Dual Turnout Dispatched",
        description: "MBMC-FE-01 (Tender Alpha 1) & MBMC-FE-04 (Bronto Skylift 55) turned out.",
        author: "Dispatcher EOC-01",
        type: "DISPATCH",
      },
      {
        id: "TL-03",
        timestamp: "14:40:22",
        title: "Units On-Scene & Size-Up",
        description: "Command established by SO Jadhav. Hydrant HYD-MR-03 tapped. Bronto 55 cage elevated.",
        author: "SO Suresh P. Jadhav",
        type: "STATUS_CHANGE",
      },
      {
        id: "TL-04",
        timestamp: "14:52:00",
        title: "46 Occupants Evacuated",
        description: "Stairwell clearing complete. 2 search teams with SCBA breathing apparatus searching Flat 803/804.",
        author: "LFM Rameshwar Gurav",
        type: "RADIO_COMMS",
      },
    ],
    sopChecklist: [
      { id: "SOP-1", task: "Verify exact GPS coordinates & best route", completed: true, completedAt: "14:33", completedBy: "EOC-01", requiredForSeverity: ["CRITICAL", "HIGH"] },
      { id: "SOP-2", task: "Dispatch First-Due Engine & Aerial Ladder", completed: true, completedAt: "14:34", completedBy: "EOC-01", requiredForSeverity: ["CRITICAL"] },
      { id: "SOP-3", task: "Alert MBMC Water Works for line pressure boost", completed: true, completedAt: "14:38", completedBy: "EOC-01", requiredForSeverity: ["CRITICAL", "HIGH"] },
      { id: "SOP-4", task: "Isolate Building Electric Mains (MSEDCL)", completed: true, completedAt: "14:45", completedBy: "SO Jadhav", requiredForSeverity: ["CRITICAL"] },
      { id: "SOP-5", task: "Complete 360-degree size-up & ICS post establishment", completed: true, completedAt: "14:48", completedBy: "SO Jadhav", requiredForSeverity: ["CRITICAL"] },
      { id: "SOP-6", task: "Primary & Secondary search of affected floor", completed: true, completedAt: "15:05", completedBy: "LFM Gurav", requiredForSeverity: ["CRITICAL"] },
      { id: "SOP-7", task: "Confirm zero toxic gas buildup with multigas detector", completed: false, requiredForSeverity: ["CRITICAL"] },
    ],
  },
  {
    id: "INC-2026-00420",
    incidentNumber: "INC-2026-00420",
    title: "Industrial Solvent Warehouse Chemical Fire",
    type: "Industrial / Chemical Hazmat",
    severity: "CRITICAL",
    status: "ON_SCENE",
    reportedAt: "2026-09-10T14:10:00.000Z",
    callerName: "Factory Manager Anand Mehta",
    callerPhone: "+91 97690 11200",
    location: {
      address: "Plot 42-B, MIDC Industrial Estate, Phase II",
      landmark: "Near Subhash Chandra Bose Road crossway",
      ward: "Ward 3 - Bhayandar East",
      zone: "Zone B (Industrial)",
      lat: 19.2978,
      lng: 72.8655,
      gridRef: "MB-BE-14D",
    },
    leadStationId: "STN-03",
    leadStationName: "Station 3 - Bhayandar East (MIDC)",
    assignedUnits: [
      {
        unitId: "MBMC-FE-06",
        callSign: "Foam Strike 06",
        type: "Foam Crash Tender",
        stationName: "Station 3 - Bhayandar East (MIDC)",
        dispatchedAt: "14:12:00",
        etaMinutes: 0,
        status: "ON_SCENE",
        crewCount: 5,
        commander: "Vinod M. Gharat (SO)",
      },
      {
        unitId: "MBMC-FE-07",
        callSign: "Hazmat Recon 07",
        type: "Hazmat Unit",
        stationName: "Station 3 - Bhayandar East (MIDC)",
        dispatchedAt: "14:13:30",
        etaMinutes: 0,
        status: "ON_SCENE",
        crewCount: 4,
        commander: "Mahesh A. Joshi (Sub-O)",
      },
    ],
    casualtiesReported: 1,
    peopleEvacuated: 85,
    structuresAtRisk: 2,
    waterSupplyStatus: "TANKER_FEED",
    hazmatPresent: true,
    hazmatDetails: "UN 1294 (Toluene / Industrial Solvent drums) - Class 3 Flammable Liquid",
    windSpeedKmh: 14.8,
    windDirection: "WSW (245°)",
    radioChannel: "CH-02 (154.570 MHz)",
    cadNotes: "Heavy AFFF foam blanket application in progress on drum storage bay. 200-meter safety cordon enforced by Navghar Police. 1 factory worker treated for minor smoke inhalation and stabilized.",
    timeline: [
      {
        id: "TL-20-01",
        timestamp: "14:10:00",
        title: "Industrial Emergency Escalation",
        description: "Solvent barrel rupture ignited during forklift loading.",
        author: "MIDC Hot-Line",
        type: "DISPATCH",
      },
      {
        id: "TL-20-02",
        timestamp: "14:15:30",
        title: "Hazmat Class 3 Protocol Initiated",
        description: "Foam Strike 06 and Hazmat Recon 07 dispatched with AFFF 3% foam.",
        author: "SO Vinod M. Gharat",
        type: "HAZMAT_ALERT",
      },
      {
        id: "TL-20-03",
        timestamp: "14:45:00",
        title: "Foam Blanket 80% Achieved",
        description: "Vapor suppression holding steady. Thermal camera reading surface at 68°C down from 240°C.",
        author: "Sub-O Mahesh Joshi",
        type: "STATUS_CHANGE",
      },
    ],
    sopChecklist: [
      { id: "SOP-1", task: "Identify UN number and chemical placard", completed: true, completedAt: "14:16", completedBy: "Sub-O Joshi", requiredForSeverity: ["CRITICAL"] },
      { id: "SOP-2", task: "Establish 200m Hot, Warm, and Cold Isolation Zones", completed: true, completedAt: "14:22", completedBy: "SO Gharat", requiredForSeverity: ["CRITICAL"] },
      { id: "SOP-3", task: "Deploy Foam / AFFF dry chemical lines", completed: true, completedAt: "14:26", completedBy: "SO Gharat", requiredForSeverity: ["CRITICAL"] },
      { id: "SOP-4", task: "Contain runoff from reaching public drainage creek", completed: true, completedAt: "14:50", completedBy: "Hazmat Team", requiredForSeverity: ["CRITICAL"] },
    ],
  },
  {
    id: "INC-2026-00419",
    incidentNumber: "INC-2026-00419",
    title: "Commercial Restaurant Duct Fire",
    type: "Commercial Complex Fire",
    severity: "HIGH",
    status: "EN_ROUTE",
    reportedAt: "2026-09-10T15:15:00.000Z",
    callerName: "Farooq K. Shaikh (Store Mgr)",
    callerPhone: "+91 91678 99312",
    location: {
      address: "Shop 14-16, Pleasant Park Commercial Hub",
      landmark: "Near Pleasant Park Garden, Mira Road (W)",
      ward: "Ward 2 - Mira Road West",
      zone: "Zone A (Commercial)",
      lat: 19.2715,
      lng: 72.879,
      gridRef: "MB-MR-04C",
    },
    leadStationId: "STN-04",
    leadStationName: "Station 4 - Kashimira",
    assignedUnits: [
      {
        unitId: "MBMC-FE-03",
        callSign: "QRV Rapid 03",
        type: "Quick Response Vehicle (QRV)",
        stationName: "Station 4 - Kashimira",
        dispatchedAt: "15:17:00",
        etaMinutes: 2,
        status: "EN_ROUTE",
        crewCount: 4,
        commander: "Anil B. Deshmukh (SO)",
      },
    ],
    casualtiesReported: 0,
    peopleEvacuated: 24,
    structuresAtRisk: 1,
    waterSupplyStatus: "HYDRANT_CONNECTED",
    hazmatPresent: false,
    windSpeedKmh: 14.8,
    windDirection: "WSW (245°)",
    radioChannel: "CH-01 (156.800 MHz)",
    cadNotes: "Kitchen exhaust grease trap fire. Staff discharged 2 ABC dry powder extinguishers. QRV Rapid 03 inbound with thermal imager and CO2 / water fog lines.",
    timeline: [
      {
        id: "TL-19-01",
        timestamp: "15:15:00",
        title: "Call Received via 101",
        description: "Flames noticed in commercial kitchen chimney exhaust.",
        author: "CAD Operator P. More",
        type: "DISPATCH",
      },
      {
        id: "TL-19-02",
        timestamp: "15:17:00",
        title: "QRV Dispatched",
        description: "MBMC-FE-03 rolling from Kashimira Station with siren.",
        author: "Dispatcher EOC-01",
        type: "DISPATCH",
      },
    ],
    sopChecklist: [
      { id: "SOP-1", task: "Verify Commercial LPG cylinder bank shutoff", completed: true, completedAt: "15:18", completedBy: "Caller Confirmed", requiredForSeverity: ["HIGH"] },
      { id: "SOP-2", task: "Thermal probe inspection of rooftop ductwork", completed: false, requiredForSeverity: ["HIGH"] },
    ],
  },
  {
    id: "INC-2026-00418",
    incidentNumber: "INC-2026-00418",
    title: "Electrical Distribution Transformer Sparking",
    type: "Electrical Substation Fire",
    severity: "MEDIUM",
    status: "RESOLVED",
    reportedAt: "2026-09-10T11:20:00.000Z",
    callerName: "Traffic Constable S. Rathod",
    callerPhone: "+91 98210 55600",
    location: {
      address: "Junction Box 11KV, Kashimira Flyover Service Rd",
      landmark: "Near Hotel Fountain Western Express Hwy",
      ward: "Ward 5 - Kashimira & WEH",
      zone: "Zone C (Highway)",
      lat: 19.2625,
      lng: 72.8835,
      gridRef: "MB-KM-02A",
    },
    leadStationId: "STN-04",
    leadStationName: "Station 4 - Kashimira",
    assignedUnits: [],
    casualtiesReported: 0,
    peopleEvacuated: 0,
    structuresAtRisk: 0,
    waterSupplyStatus: "HYDRANT_CONNECTED",
    hazmatPresent: false,
    windSpeedKmh: 12.0,
    windDirection: "W (270°)",
    radioChannel: "CH-01 (156.800 MHz)",
    cadNotes: "MSEDCL line trip confirmed. CO2 extinguishers applied. Area safely turned over to power distribution engineers at 12:05.",
    timeline: [
      {
        id: "TL-18-01",
        timestamp: "11:20:00",
        title: "Call Logged",
        description: "Sparks observed on 11KV step-down transformer.",
        author: "CAD Operator R. Dave",
        type: "DISPATCH",
      },
      {
        id: "TL-18-02",
        timestamp: "12:05:00",
        title: "Incident Closed",
        description: "Transformer cold, no fire spread. Operations normal.",
        author: "SO Deshmukh",
        type: "RESOLUTION",
      },
    ],
    sopChecklist: [],
  },
  {
    id: "INC-2026-00417",
    incidentNumber: "INC-2026-00417",
    title: "Coastal Fishing Trawler Engine Smolder",
    type: "Coastal / Creek Rescue",
    severity: "LOW",
    status: "RESOLVED",
    reportedAt: "2026-09-10T09:15:00.000Z",
    callerName: "Uttan Koli Samaj President",
    callerPhone: "+91 98920 11988",
    location: {
      address: "Berth No. 4, Uttan Coastal Jetty",
      landmark: "Near Uttan Velankanni Shrine Road",
      ward: "Ward 6 - Uttan & Coastal",
      zone: "Zone D (Coastal)",
      lat: 19.281,
      lng: 72.784,
      gridRef: "MB-UT-01C",
    },
    leadStationId: "STN-05",
    leadStationName: "Station 5 - Uttan Coastal Sub-Station",
    assignedUnits: [],
    casualtiesReported: 0,
    peopleEvacuated: 6,
    structuresAtRisk: 1,
    waterSupplyStatus: "CREEK_DRAFTING",
    hazmatPresent: false,
    windSpeedKmh: 18.2,
    windDirection: "SW (225°)",
    radioChannel: "CH-04 (162.400 MHz)",
    cadNotes: "Diesel engine overheating resolved with portable foam and salt-water cooling hose. Zero hull damage.",
    timeline: [],
    sopChecklist: [],
  },
];

export const MOCK_PERSONNEL: Personnel[] = [
  {
    id: "MBMC-FD-101",
    badgeNumber: "MBMC-001",
    name: "Dr. Arvind V. Shinde",
    rank: "Chief Fire Officer (CFO)",
    stationId: "STN-02",
    stationName: "Station 2 - Bhayandar West Central",
    shift: "SHIFT_ALPHA (08:00 - 16:00)",
    dutyStatus: "ON_DUTY_AVAILABLE",
    specializations: ["Incident Command System (ICS)", "Hazmat Specialist"],
    phone: "+91 98200 12001",
    bloodGroup: "O+",
    emergencyContact: "Mrs. Shinde (+91 98200 12002)",
    yearsOfService: 24,
    lastMedicalCheck: "2026-06-15",
  },
  {
    id: "MBMC-FD-102",
    badgeNumber: "MBMC-004",
    name: "Kailash R. Patil",
    rank: "Divisional Fire Officer (DFO)",
    stationId: "STN-02",
    stationName: "Station 2 - Bhayandar West Central",
    shift: "SHIFT_ALPHA (08:00 - 16:00)",
    dutyStatus: "ON_DUTY_AVAILABLE",
    specializations: ["Incident Command System (ICS)", "High-Angle Rope Rescue"],
    phone: "+91 98200 12004",
    bloodGroup: "B+",
    emergencyContact: "Mr. Patil (+91 98200 12005)",
    yearsOfService: 19,
    lastMedicalCheck: "2026-07-10",
  },
  {
    id: "MBMC-FD-103",
    badgeNumber: "MBMC-012",
    name: "Suresh P. Jadhav",
    rank: "Station Officer (SO)",
    stationId: "STN-01",
    stationName: "Station 1 - Mira Road East",
    shift: "SHIFT_ALPHA (08:00 - 16:00)",
    dutyStatus: "DEPLOYED_ACTIVE",
    specializations: ["Incident Command System (ICS)", "Breathing Apparatus (BA) Expert", "Thermal Imaging Recon"],
    phone: "+91 98200 12012",
    bloodGroup: "A+",
    emergencyContact: "Mrs. Jadhav (+91 98200 12013)",
    yearsOfService: 15,
    assignedVehicleId: "MBMC-FE-01",
    assignedIncidentId: "INC-2026-00421",
    heartRateBpm: 92,
    oxygenLevelPct: 98,
    lastMedicalCheck: "2026-08-01",
  },
  {
    id: "MBMC-FD-104",
    badgeNumber: "MBMC-018",
    name: "Vinod M. Gharat",
    rank: "Station Officer (SO)",
    stationId: "STN-03",
    stationName: "Station 3 - Bhayandar East (MIDC)",
    shift: "SHIFT_ALPHA (08:00 - 16:00)",
    dutyStatus: "DEPLOYED_ACTIVE",
    specializations: ["Hazmat Specialist", "Hydraulic Extrication"],
    phone: "+91 98200 12018",
    bloodGroup: "AB+",
    emergencyContact: "Mrs. Gharat (+91 98200 12019)",
    yearsOfService: 16,
    assignedVehicleId: "MBMC-FE-06",
    assignedIncidentId: "INC-2026-00420",
    heartRateBpm: 98,
    oxygenLevelPct: 97,
    lastMedicalCheck: "2026-05-20",
  },
  {
    id: "MBMC-FD-105",
    badgeNumber: "MBMC-022",
    name: "Anil B. Deshmukh",
    rank: "Station Officer (SO)",
    stationId: "STN-04",
    stationName: "Station 4 - Kashimira",
    shift: "SHIFT_ALPHA (08:00 - 16:00)",
    dutyStatus: "DEPLOYED_ACTIVE",
    specializations: ["Breathing Apparatus (BA) Expert", "Thermal Imaging Recon"],
    phone: "+91 98200 12022",
    bloodGroup: "O+",
    emergencyContact: "Mr. Deshmukh (+91 98200 12023)",
    yearsOfService: 12,
    assignedVehicleId: "MBMC-FE-03",
    assignedIncidentId: "INC-2026-00419",
    heartRateBpm: 84,
    oxygenLevelPct: 99,
    lastMedicalCheck: "2026-07-28",
  },
  {
    id: "MBMC-FD-106",
    badgeNumber: "MBMC-035",
    name: "Rameshwar Gurav",
    rank: "Leading Fireman (LFM)",
    stationId: "STN-01",
    stationName: "Station 1 - Mira Road East",
    shift: "SHIFT_ALPHA (08:00 - 16:00)",
    dutyStatus: "DEPLOYED_ACTIVE",
    specializations: ["High-Angle Rope Rescue", "Breathing Apparatus (BA) Expert"],
    phone: "+91 98200 12035",
    bloodGroup: "B-",
    emergencyContact: "Mrs. Gurav (+91 98200 12036)",
    yearsOfService: 10,
    assignedVehicleId: "MBMC-FE-04",
    assignedIncidentId: "INC-2026-00421",
    heartRateBpm: 105,
    oxygenLevelPct: 96,
    lastMedicalCheck: "2026-08-14",
  },
  {
    id: "MBMC-FD-107",
    badgeNumber: "MBMC-041",
    name: "Dinesh K. Sawant",
    rank: "Driver-Cum-Pump-Operator (DCPO)",
    stationId: "STN-01",
    stationName: "Station 1 - Mira Road East",
    shift: "SHIFT_ALPHA (08:00 - 16:00)",
    dutyStatus: "DEPLOYED_ACTIVE",
    specializations: ["Hydraulic Extrication"],
    phone: "+91 98200 12041",
    bloodGroup: "O-",
    emergencyContact: "Mrs. Sawant (+91 98200 12042)",
    yearsOfService: 8,
    assignedVehicleId: "MBMC-FE-01",
    assignedIncidentId: "INC-2026-00421",
    heartRateBpm: 78,
    oxygenLevelPct: 99,
    lastMedicalCheck: "2026-06-25",
  },
  {
    id: "MBMC-FD-108",
    badgeNumber: "MBMC-048",
    name: "Ganesh T. Mhatre",
    rank: "Sub-Officer (Sub-O)",
    stationId: "STN-05",
    stationName: "Station 5 - Uttan Coastal Sub-Station",
    shift: "SHIFT_ALPHA (08:00 - 16:00)",
    dutyStatus: "ON_DUTY_AVAILABLE",
    specializations: ["Underwater / Coastal Diver", "Incident Command System (ICS)"],
    phone: "+91 98200 12048",
    bloodGroup: "A-",
    emergencyContact: "Mr. Mhatre (+91 98200 12049)",
    yearsOfService: 11,
    lastMedicalCheck: "2026-07-04",
  },
];

export const MOCK_WARD_METRICS: WardMetric[] = [
  {
    wardId: "WARD-1",
    wardName: "Ward 1 - Mira Road East (Kanakia/Beverly)",
    totalIncidents30d: 38,
    avgResponseMinutes: 5.2,
    activeHydrants: 24,
    riskScore: 78,
    primaryStation: "Station 1 - Mira Road East",
  },
  {
    wardId: "WARD-2",
    wardName: "Ward 2 - Mira Road West (Shanti Park)",
    totalIncidents30d: 22,
    avgResponseMinutes: 5.6,
    activeHydrants: 18,
    riskScore: 54,
    primaryStation: "Station 1 - Mira Road East",
  },
  {
    wardId: "WARD-3",
    wardName: "Ward 3 - Bhayandar East (MIDC Industrial)",
    totalIncidents30d: 45,
    avgResponseMinutes: 4.8,
    activeHydrants: 32,
    riskScore: 89,
    primaryStation: "Station 3 - Bhayandar East (MIDC)",
  },
  {
    wardId: "WARD-4",
    wardName: "Ward 4 - Bhayandar West (Railway & Town)",
    totalIncidents30d: 29,
    avgResponseMinutes: 5.0,
    activeHydrants: 26,
    riskScore: 61,
    primaryStation: "Station 2 - Bhayandar West",
  },
  {
    wardId: "WARD-5",
    wardName: "Ward 5 - Kashimira & WEH Corridor",
    totalIncidents30d: 34,
    avgResponseMinutes: 5.4,
    activeHydrants: 20,
    riskScore: 72,
    primaryStation: "Station 4 - Kashimira",
  },
  {
    wardId: "WARD-6",
    wardName: "Ward 6 - Uttan Coastal & Dongri",
    totalIncidents30d: 12,
    avgResponseMinutes: 6.9,
    activeHydrants: 14,
    riskScore: 38,
    primaryStation: "Station 5 - Uttan Coastal Sub-Station",
  },
];

export const MOCK_RESPONSE_METRICS: ResponseTimeMetric[] = [
  { timeSlot: "00:00 - 04:00", turnoutSeconds: 45, travelSeconds: 240, totalSeconds: 285, benchmarkGoalSeconds: 420 },
  { timeSlot: "04:00 - 08:00", turnoutSeconds: 42, travelSeconds: 260, totalSeconds: 302, benchmarkGoalSeconds: 420 },
  { timeSlot: "08:00 - 12:00", turnoutSeconds: 52, travelSeconds: 340, totalSeconds: 392, benchmarkGoalSeconds: 420 },
  { timeSlot: "12:00 - 16:00", turnoutSeconds: 50, travelSeconds: 310, totalSeconds: 360, benchmarkGoalSeconds: 420 },
  { timeSlot: "16:00 - 20:00", turnoutSeconds: 54, travelSeconds: 370, totalSeconds: 424, benchmarkGoalSeconds: 420 },
  { timeSlot: "20:00 - 00:00", turnoutSeconds: 48, travelSeconds: 290, totalSeconds: 338, benchmarkGoalSeconds: 420 },
];

export const MOCK_INCIDENT_TYPE_DISTRIBUTION: IncidentTypeDistribution[] = [
  { type: "High-Rise Building Rescue", count: 48, percentage: 34, color: "#EF4444" },
  { type: "Industrial / Chemical Hazmat", count: 32, percentage: 23, color: "#F97316" },
  { type: "Commercial Complex Fire", count: 26, percentage: 18, color: "#F59E0B" },
  { type: "Electrical Substation / Transformer", count: 18, percentage: 13, color: "#3B82F6" },
  { type: "Vehicular Accident / Rescue", count: 12, percentage: 8, color: "#06B6D4" },
  { type: "Coastal / Creek Rescue", count: 6, percentage: 4, color: "#10B981" },
];

export const MOCK_COMPLIANCE_REPORTS: ComplianceReport[] = [
  {
    id: "REP-2026-089",
    reportNumber: "MBMC-FIR-2026-AUG-W3",
    title: "Monthly MIDC Industrial Hazard & Water Hydrant Pressure Audit",
    date: "2026-08-31",
    ward: "Ward 3 - Bhayandar East",
    station: "Station 3 - Bhayandar East (MIDC)",
    author: "Vinod M. Gharat (SO)",
    status: "APPROVED",
    incidentsCovered: 45,
    summary: "All 32 industrial hydrants in MIDC Sector 1, 2, and 3 inspected. Static pressure averaged 5.8 bar. 2 hydrants serviced and gaskets replaced.",
    responseCompliancePct: 97.4,
  },
  {
    id: "REP-2026-088",
    reportNumber: "MBMC-FIR-2026-AUG-W1",
    title: "High-Rise Fire Safety System Verification Dossier (Kanakia/Beverly)",
    date: "2026-08-28",
    ward: "Ward 1 - Mira Road East",
    station: "Station 1 - Mira Road East",
    author: "Suresh P. Jadhav (SO)",
    status: "APPROVED",
    incidentsCovered: 38,
    summary: "Mandatory Form B fire safety certificates audited across 64 residential towers exceeding 22 floors. 12 notices issued for dry riser maintenance.",
    responseCompliancePct: 96.1,
  },
  {
    id: "REP-2026-087",
    reportNumber: "MBMC-FIR-2026-SEP-CUR",
    title: "Weekly Shift Turnover & Emergency Apparatus Telemetry Summary",
    date: "2026-09-08",
    ward: "All Wards (MBMC Central)",
    station: "All 5 Stations",
    author: "Dr. Arvind V. Shinde (CFO)",
    status: "AUDITED",
    incidentsCovered: 18,
    summary: "Fleet operational readiness at 92.8%. MBMC-FE-14 scheduled for routine pump overhaul. Bronto Skylift hydraulic fluid pressure calibrated.",
    responseCompliancePct: 98.2,
  },
];
